version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: echo "need for build"
  reviewboard:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: echo "RB hello world"
notify:
  webhooks:
    - url: http://localhost:8080/rbintegrations/circle-ci/webhook/